ignorePaths:
  - ./**/go.mod
  - ./**/go.sum
  - ./config/crd/bases/**/*
  - ./api/v1alpha2/cloudinit/v22.3/**/*
  - ./**/bin/**/*
  - ./.golangci.yml
words:
  - abspath
  - akutz
  - apimachinery
  - authkeys
  - bryanv
  - clientset
  - Cloudbase
  - cloudinit
  - clustermodules
  - clustervirtualmachineimages
  - clustervmimage
  - commmands
  - contentlibraryproviders
  - contentsources
  - corev
  - corrieb
  - cpus
  - Cpus
  - crds
  - deepcopy
  - derekbeard
  - dhclient
  - envtest
  - expiredate
  - faillog
  - finalizers
  - gecos
  - GOARCH
  - golangci
  - GOLANGCI
  - gomega
  - GOSC
  - govmomi
  - groupname
  - guestinfo
  - gzipped
  - ifneq
  - imageregistry
  - intstr
  - koalaman
  - kubebuilder
  - kubedns
  - Kutz
  - lastlog
  - linklayer
  - Linuxprep
  - markdownlint
  - mdlrc
  - metav
  - mivok
  - mykey
  - nolint
  - openapi
  - OSID
  - Prereq
  - prereqs
  - printcolumn
  - proxying
  - resourcepool
  - Roadmap
  - rpctool
  - runcmd
  - shellcheck
  - snapuser
  - SRIOV
  - storageVersion
  - stylecheck
  - subnetmask
  - subresource
  - substr
  - Sysrep
  - systcl
  - Systeprep
  - tanzu
  - templating
  - unexported
  - userdata
  - utilruntime
  - VADP
  - Venteicher
  - vgpu
  - VGPU
  - virtualmachineclasses
  - virtualmachinedefaults
  - virtualmachinedeployments
  - virtualmachineimages
  - virtualmachinereplicasets
  - virtualmachines
  - virtualmachineservices
  - virtualmachinesetresourcepolicies
  - vmclass
  - vmclassbinding
  - vmdefault
  - vmdefaults
  - vmdeployment
  - vmimage
  - VMIP
  - Vmop
  - vmoperator
  - vmpr
  - vmpub
  - vmreplicaset
  - vmrs
  - vmservice
  - VMTX
  - workdir
  - zoneinfo
